### PR TITLE
Feature/wgpu

### LINKED ISSUE #18: [Editor] Dedicated editor camera component & system

### LINKED ISSUE #27: WebGPU Integration
- [ ] WebGPU Renderer
- [ ] WebGPU Rendering System, Component
- [ ] WebGPU Shader
- [ ] WebGPU Texture
- [ ] WebGPU Material

### PR DESCRIPTION
**Pull request by johnoyo**
## Description
Adds the WebGPU API into the framework.
- WebGPU window.
- WebGPU Renderer:
    - Uses instanced drawing (the OpenGL renderer will use this design as well soon),
    - Support for multiple render passes.
- WebGPU rendering system + component:
    - Rendering and Material component will be merged with the OpenGL ones soon.

## Related issues
- Closes #27 
- Closes #18

### CODE REVIEW

**Comment by stratosger** [comment]
WGPU examples work on my end 🎉

**Review by kamarianakis — APPROVED** [review]
LGTM

**Comment by aprotopsaltis** [comment]
giving my review comments, even though the PR was closed:

OpenGL 
example00: great!
example01:  while rotating faces don't always show
example02: great!
example03 / example04 / example05:
	- great!
	- scaling down camera too much: gives nan and does not recover values
	- adding a light component on monkeh: changes the light parameters of the pistol. Probably due to all entities using the same shaders.

WebGPU 
example00: great!
example01: pistol and monkeh all good, but with keys 1 and 2, e1 and e2 should be selected, but no entities with this name
example02: after multiple times of pressing space to change the scene the program crashes with error: Vertex buffer index 16 is greater than the device's requested `max_vertex_buffers` limit 16

**Comment by johnoyo** [comment]
> giving my review comments, even though the PR was closed:
> 
> OpenGL example00: great! example01: while rotating faces don't always show example02: great! example03 / example04 / example05: - great! - scaling down camera too much: gives nan and does not recover values - adding a light component on monkeh: changes the light parameters of the pistol. Probably due to all entities using the same shaders.
> 
> WebGPU example00: great! example01: pistol and monkeh all good, but with keys 1 and 2, e1 and e2 should be selected, but no entities with this name example02: after multiple times of pressing space to change the scene the program crashes with error: Vertex buffer index 16 is greater than the device's requested `max_vertex_buffers` limit 16

Added an issue for this (https://github.com/papagiannakis/pyGandalf/issues/37), Thanks!

**Pull request merged**
