### PR TITLE
Feature/main skeleton and setup

### LINKED ISSUE #2: Repository set up
Set up the repository and all the dependencies.

### LINKED ISSUE #3: Framework runtime core
Implement the core skeleton of the frame work
- Application
- Window
- SceneManager

### LINKED ISSUE #4: Entity Component System deployment
- Create a robust, extendable and simple ecs framework following the main principles of ecs.
- Create the first vital systems and components
    - [x] Transform
    - [x] Link
    - [x] OpenGLRendering

### PR DESCRIPTION
**Pull request by johnoyo**
## Description
- Set up repo, dependencies and packages with [pdm](https://pdm-project.org/latest/).
- Added core framework code:
    - Application, Window and SceneManager classes,
    - ECS core functionality:
        - Systems:
            - TransformSystem,
            - LinkSystem,
            - OpenGLRenderingSystem:
               - Renderer, Materials, Shaders, Textures.
         - Components:
            - TransformComponent,
            - LinkComponent,
            - OpenGLRenderComponent,
            - InfoComponent.
    - Logger
- Added first iteration of unit tests:
    - Unit tests for basic ecs functionality,
    - Unit tests for basic scene functionality.
- Added 2 temporary examples:
     - example00: hierachical 2d quads,
     - example01: ecss rotating cube.
- Updated README.

## Related Issues
- Closes #2 
- Closes #3 
- Closes #4

### CODE REVIEW

**Comment by kamarianakis** [comment]
Update pathing issues: mac and windows handle pathing (e.g. '../shaders/' in a different way). The same issue was resolved in Elements using the pathlib library and pathing relative to the ROOT directory (shortcuts can be added in the definitions.py). I also suggest that we do not hide textures, shaders, etc within the examples directory and simply add them in a files directory, in the same level as examples (we will then only need update the definitions.py and add proper pathing for textures and shaders folders)

**Comment by kamarianakis** [comment]
Currently I am running tests successfully but I am getting the following message, I will investigate further: 

/Users/manos/opt/anaconda3/envs/gandalf/lib/python3.10/site-packages/glfw/__init__.py:914: GLFWError: (65543) b'NSGL: The targeted version of macOS only supports forward-compatible core profile contexts for OpenGL 3.2 and above'
  warnings.warn(message, GLFWError)
CRITICAL - Window could not be created!

**Comment by stratosger** [comment]
Easy to install and get it running, thanks for the detailed instructions. 👍 

I ran the tests successfully, but when trying to run an example, it is failing with the message below:

`2024-03-08 08:26:04,792 - INFO - OpenGL 4.1 Metal - 88 GLSL 4.10 Renderer Apple M2 Max
Traceback (most recent call last):
  File "/Users/stratosg/pyGandalf/src/examples/OpenGL/example00.py", line 166, in <module>
    main()
  File "/Users/stratosg/pyGandalf/src/examples/OpenGL/example00.py", line 103, in main
    OpenGLShaderLib().build('textured_colored_blue', textured_vertex_shader_code, textured_fragment_shader_code_blue)
  File "/Users/stratosg/pyGandalf/src/utilities/opengl_shader_lib.py", line 52, in build
    shader_program = cls.instance.create_shader_program(vertex_shader_code, fragment_shader_code)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stratosg/pyGandalf/src/utilities/opengl_shader_lib.py", line 41, in create_shader_program
    raise RuntimeError(gl.glGetProgramInfoLog(shader_program).decode('utf-8'))
RuntimeError: ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 32 samplers`

Tested it on macOS 14.3.1

**Comment by stratosger** [comment]
After commit df479de9e795b2138947d8ce69e816a028ae4c81 it works fully on my end! 🎉

**Comment by kamarianakis** [comment]
Latest version works on my mac!

**Pull request merged**
